[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[window]
startup_mode = "Maximized"
opacity = 0.95
decorations = "Full"

[font]
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
bold = { family = "SauceCodePro Nerd Font Mono", style = "Bold" }
italic = { family = "SauceCodePro Nerd Font Mono", style = "Italic" }
bold_italic = { family = "SauceCodePro Nerd Font Mono", style = "BoldItalic" }
size = 11.0

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500

[terminal]
shell = { program = "/bin/zsh", args = ["-c", "tmux attach || tmux"] }

[keyboard]
bindings = [
  # Copiar e colar (clipboard do sistema)
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },

  # Zoom in/out e reset
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus",  mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0",   mods = "Control", action = "ResetFontSize" },

  # Scroll
  { key = "PageUp",   action = "ScrollPageUp" },
  { key = "PageDown", action = "ScrollPageDown" }
]

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"
